### ISSUE TITLE
Missing Characters-bot SQL!!

### ISSUE THREAD

**Issue by mygithome002** [jokerlfm/ShiShi#2]
**Description**:

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by jokerlfm** [comment]
bots sql could use lidocian bots sql
https://github.com/Lidocian/Playerbot-sqls
https://github.com/Lidocian/Playerbot-sqls.git

**Comment by jokerlfm** [comment]
And in characters_ai_playerbot_custom_strategy.sql  
He misses a ','

**Comment by mygithome002** [comment]
Thanks.
After woldserver run,"server.log"was huge;and bot doesnot follow into instance.

**Comment by jokerlfm** [comment]
So there are still a lot work to do.

**Comment by mygithome002** [comment]
bot branch :login into game,authserver crash.i complie twice,both crash.

**Comment by muches** [comment]
Hunter pet summon cause crashes
